name: Build and Push Docker Image

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: docker

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Forgejo Container Registry
      uses: docker/login-action@v3
      with:
        username: ${{ vars.FORGEJO_USERNAME }}
        password: ${{ secrets.FORGEJO_TOKEN }}

    - name: Build and push Docker image
      id: build
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ${{ vars.REGISTRY }}/${{ vars.IMAGE_NAME }}:latest
        cache-from: type=registry,ref=${{ vars.REGISTRY }}/${{ vars.IMAGE_NAME }}:latest
        cache-to: type=inline,dest=image.cache
        platforms: linux/amd64,linux/arm64
        build-args: |
          GIT_COMMIT=${{ github.sha }}
          BUILD_DATE=$(date -u +"%Y-%m-%d")
        no-cache: false
        output: json

    - name: Display build output
      run: |
        echo "Build completed successfully"
        echo "Image pushed to Forgejo Container Registry: ${{ vars.REGISTRY }}/${{ vars.IMAGE_NAME }}:latest"

    - name: Clean up old images
      run: docker image prune -f

    - name: Display build summary
      run: |
        echo "Build Summary:"
        echo "${{ steps.build.outputs.summary }}"